### ISSUE TITLE
Seperate functions

### ISSUE THREAD

**Issue by astray-heavy-arms** [DD-Z3ro/learning_python#1]
https://github.com/DD-Z3ro/learning_python/blob/f8805f620cb3ffa6eb0e3b820cfe4657890a7761/shopping_list.py#L46C5-L50C35

Expand this function into two keep class methods so they're more "pure"

One function for the name of the item you want to add.
One function for the item count.

**Comment by DD-Z3ro** [comment]
Separated function into input_item and input_amount.
