### ISSUE TITLE
Issue with removing items

### ISSUE THREAD

**Issue by astray-heavy-arms** [DD-Z3ro/learning_python#2]
https://github.com/DD-Z3ro/learning_python/blob/f8805f620cb3ffa6eb0e3b820cfe4657890a7761/shopping_list.py#L26

--

This function needs more work. We have to make sure if the item exists in the list currently THEN remove it.

**Comment by DD-Z3ro** [comment]
fixed, now checks to see if item is in the list, if not informs them it doesn't. Will be in next push.
