### ISSUE TITLE
Store the list as an dictionary

### ISSUE THREAD

**Issue by astray-heavy-arms** [DD-Z3ro/learning_python#5]
When I add milk or Milk, it creates two entries rather than one as it's the same thing. I'm starting to the think the shopping list would be better as a dictionary to store the data. This way we can store items along with their count.

Something like : -

```
shopping_list = {
    'milk': 2,
    'cheese': 4
}
```

Output
---

milk has been added with an amount of6
Milk:6
milk:6
None

What should happen 
---

There should be no difference between a user adding Milk or milk it should be a single entry and the count should be 12.

**Comment by DD-Z3ro** [comment]
What if we made a prompt for it to ask if they would like to re-adjust the value of the item?

**Comment by astray-heavy-arms** [comment]
No it's poor design to ask a user to re-adjust the value of an item if the item is Milk or milk.

List items should be stored lowercase so if a user adds Milk or milk the items count is the same.

**Comment by DD-Z3ro** [comment]
Fixed now, adds items to list in lowercase and now prompts when an item already exists on the list if they want to change its value. Will be in next push.
